ALTER TABLE review_task ADD COLUMN created_at TIMESTAMP(6) NULL, ADD COLUMN sla_due_at TIMESTAMP(6) NULL;
UPDATE review_task SET created_at=CURRENT_TIMESTAMP(6),sla_due_at=TIMESTAMPADD(HOUR,2,CURRENT_TIMESTAMP(6)) WHERE created_at IS NULL;
ALTER TABLE review_task MODIFY created_at TIMESTAMP(6) NOT NULL, MODIFY sla_due_at TIMESTAMP(6) NOT NULL;
